services:
  # Splunk Enterprise server
  splunk-ccloud:
    image: splunk/splunk:latest
    platform: linux/amd64
    container_name: splunk-ccloud
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-0000000000000
      - SPLUNK_PASSWORD=changeme
    ports:
      - 18000:8000
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000' ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./splunk.yml:/tmp/defaults/default.yml
      - splunk_var:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc

volumes:
  splunk_var: {}
  splunk_etc: {}